import { ArrowLeft, Copy, Dices, RefreshCw, Sparkles } from 'lucide-react'
import { useState } from 'react'

const styles = [
  ['Riso / Grain Rave', 'raw photocopy duotone, heavy risograph grain and slight two-colour misregistration', 'rough hand-cut type, circular stamp marks and a torn-paper frame'],
  ['Frutiger-Aero', 'icy silver-blue halftone screen with pearlescent paper and clean chrome reflections', 'glass capsule shapes, soft cyan glow and inflated techno lettering'],
  ['Brutalist Signal', 'matte black ink, bone-white stock and sharp fluorescent lime registration marks', 'monumental condensed type, utility labels and a severe broken grid'],
  ['Xerox Romance', 'blown-out black-and-cream photocopy texture, tape marks and visible paper fibres', 'an intimate found-image collage, marker strokes and cropped editorial copy'],
  ['Chrome Ritual', 'smoked-glass shadows, polished aluminum surfaces and controlled foil highlights', 'a single surreal object, laser-etched coordinates and architectural spacing'],
] as const
const formats = ['Rave flyer', 'Single poster', 'Album cover', 'Art print', 'Campaign poster', 'Zine cover']
const fallback = ['a midnight radio station', 'a coastal gear label', 'an all-night noodle bar', 'a moth collector’s field archive', 'a warehouse dance crew', 'a decommissioned lighthouse']
const pick = <T,>(values: readonly T[]) => values[Math.floor(Math.random() * values.length)]

export default function Destiny() {
  const [subject, setSubject] = useState(''); const [style, setStyle] = useState(0); const [format, setFormat] = useState(formats[0]); const [headline, setHeadline] = useState(''); const [prompt, setPrompt] = useState(''); const [history, setHistory] = useState<string[]>([]); const [notice, setNotice] = useState('')
  const makePrompt = (random = false) => { const choice = random ? Math.floor(Math.random() * styles.length) : style; const selected = styles[choice]; const actualSubject = subject.trim() || pick(fallback); const actualFormat = random ? pick(formats) : format; const title = headline.trim() || 'invented editorial title'; const result = `${actualFormat} — ${selected[0]}. Vertical composition for ${actualSubject}; ${selected[1]}. Create ${selected[2]}. Typography: “${title}” is the structural headline, oversized, cropped and physically integrated with the image; add only restrained microcopy for date, location and catalog data. Composition is asymmetric with one decisive focal point, large controlled negative space and a strict invisible grid. Use a limited palette with one acidic accent, tactile print imperfections and intentional material detail. Quietly intelligent underground culture, premium graphic design, no generic AI gloss, no random clutter, 4:5 vertical.`; setStyle(choice); setFormat(actualFormat); setPrompt(result); setHistory(old => [result, ...old.filter(x => x !== result)].slice(0, 5)); setNotice(random ? 'Fresh plate randomized' : 'New plate generated'); window.setTimeout(() => setNotice(''), 1600) }
  const randomize = () => { setSubject(pick(fallback)); setHeadline(pick(['AFTER SIGNAL', 'TENDER MACHINE', 'LOW TIDE', 'SYSTEM 06', 'SLOW BURN'])); makePrompt(true) }
  return <div className="destiny-tool"><header className="destiny-header"><a href="#studio" onClick={() => window.location.reload()}><ArrowLeft size={16}/> PROMPT STUDIO</a><div><b>DESTINY<span>.</span></b><small>PROMPT PRESS</small></div><em>SESSION / {String(history.length).padStart(3, '0')}</em></header><main className="destiny-main"><section className="destiny-controls"><p>BUILD A PLATE</p><small>Choose a direction—or leave it open and let the press make a fresh pull.</small><label>SUBJECT<input value={subject} onChange={e => setSubject(e.target.value)} placeholder="e.g. a midnight radio station" /></label><label>STYLE<select value={style} onChange={e => setStyle(Number(e.target.value))}>{styles.map((item, index) => <option value={index} key={item[0]}>{item[0]}</option>)}</select></label><label>FORMAT<select value={format} onChange={e => setFormat(e.target.value)}>{formats.map(item => <option key={item}>{item}</option>)}</select></label><label>TYPE ON THE PLATE<input value={headline} onChange={e => setHeadline(e.target.value)} placeholder="headline or big word" /></label><div className="destiny-actions"><button className="destiny-primary" onClick={() => makePrompt()}><Sparkles size={16}/> RUN THE PRESS</button><button onClick={randomize}><Dices size={16}/> RANDOMIZE</button></div></section><section className="destiny-stage"><div className={`destiny-poster ${prompt ? '' : 'empty'}`}><i/><i/><i/><i/>{prompt ? <><div className="destiny-meta">DESTINY // {styles[style][0].toUpperCase()} <span>PLATE / {String(history.length).padStart(3, '0')}</span></div><b>{format.toUpperCase()}</b><pre>{prompt}</pre><footer>ACCENT — ACID LIME <span>SUBJECT — {subject || 'SURPRISE'}</span></footer></> : <p>Nothing on the plate yet.<br/>Set a direction, then run the press.</p>}</div>{prompt && <div className="destiny-output-actions"><button className="destiny-primary" onClick={() => { navigator.clipboard.writeText(prompt); setNotice('Prompt copied'); window.setTimeout(() => setNotice(''), 1600) }}><Copy size={16}/> COPY PROMPT</button><button onClick={() => makePrompt()}><RefreshCw size={16}/> PULL AGAIN</button></div>}{history.length > 0 && <div className="destiny-history"><span>RECENT PULLS</span>{history.map((item, index) => <button key={index} onClick={() => setPrompt(item)}>{item}</button>)}</div>}</section></main>{notice && <div className="lime-toast">{notice}</div>}</div>
}
